spring:
  kafka:
    listener:
      type: single
      ack-mode: record
      concurrency: 1
    properties:
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL

custom:
  trade:
    worker:
      max-money: 100    # worker 는 최대 100만원을 가지고 거래 가능
      min-money: 20     # worker 는 최소 20만원부터 거래 시작
