spring:
  kafka:
    listener:
      type: single
      ack-mode: record
      concurrency: 2
    properties:
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL
  data:
    mongodb:
      auto-index-creation: true
      uuid-representation: standard

custom:
  trade:
    worker:
      max-money: 1000000    # worker 는 최대 100만원을 가지고 거래 가능
      min-money: 200000     # worker 는 최소 20만원부터 거래 시작
