spring:
  application:
    name: "CoinTraderManager"
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME:'username'}:${MONGO_PASSWORD:'password'}@${MONGO_URL:'url'}/${MONGO_DATABASE:'db'}?retryWrites=true&w=majority
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-server}
    listener:
      client-id: "CoinTraderManager"
    consumer:
      group-id: "CoinTraderManager"
    properties:
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_API_KEY:api_key}' password='${KAFKA_API_SECRET:api_secret}';

custom:
  upbit:
    access-key: ${UPBIT_ACCESS_KEY:access-key}
    secret-key: ${UPBIT_SECRET_KEY:secret-key}
  kubernetes:
    namespace: ${KUBERNETES_NAMESPACE:default}
    image:
      pull-secret-name: ${KUBERNETES_IMAGE_PULL_SECRET_NAME:image-pull-secret}
      pull-policy: ${KUBERNETES_IMAGE_PULL_POLICY:IfNotPresent}
      name: ${KUBERNETES_IMAGE_NAME:coin-trade-worker}
    env-secret-name: ${KUBERNETES_ENV_SECRET_NAME:env-secret-name}
    kube-config-location: ${KUBERNETES_KUBECONFIG_LOCATION:/var/kube/config}
  db:
    descriptor: ${ORACLE_DESCRIPTOR:'connection-string'}
    username: ${ORACLE_USERNAME:'username'}
    password: ${ORACLE_PASSWORD:'password'}
    max-conn: ${ORACLE_MAX_CONN:3}
    min-conn: ${ORACLE_MIN_CONN:1}
  message-sender:
    url: ${MESSAGE_SENDER_URL:'url'}
    username: ${MESSAGE_SENDER_USERNAME:'username'}
    password: ${MESSAGE_SENDER_PASSWORD:'password'}