custom:
  id: ${APP_ID:app-id}
  kafka:
    url: ${KAFKA_REST_PROXY_URL:kafka-rest-proxy-url}
    cluster:
      name: ${KAFKA_CLUSTER_NAME:cluster-name}
    api:
      key: ${KAFKA_API_KEY:kafka-api-key}
      secret: ${KAFKA_API_SECRET:kafka-api-secret}
    topic:
      alarm: ${KAFKA_ALARM_TOPIC_NAME:alarm}
      trade-result: ${KAFKA_TRADE_RESULT_NAME:trade-result}
  db:
    descriptor: ${ORACLE_DESCRIPTOR:'connection-string'}
    username: ${ORACLE_USERNAME:'username'}
    password: ${ORACLE_PASSWORD:'password'}
    max-conn: ${ORACLE_MAX_CONN:3}
    min-conn: ${ORACLE_MIN_CONN:1}
  trade:
    start-market: ${START_MARKET:KRW-BTC}
    start-money: ${START_MONEY:10000}
  upbit:
    access-key: ${UPBIT_ACCESS_KEY:upbit-access-key}
    secret-key: ${UPBIT_SECRET_KEY:upbit-secret-key}



