spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME:'username'}:${MONGO_PASSWORD:'password'}@${MONGO_URL:'url'}/${MONGO_DATABASE:'db'}?${MONGO_OPTION:'retryWrites=false'}

custom:
  id: ${APP_ID:app-id}
  kafka:
    url: ${KAFKA_REST_PROXY_URL:kafka-rest-proxy-url}
    cluster:
      name: ${KAFKA_CLUSTER_NAME:cluster-name}
    api:
      key: ${KAFKA_API_KEY:kafka-api-key}
      secret: ${KAFKA_API_SECRET:kafka-api-secret}
    topic:
      alarm: ${KAFKA_ALARM_TOPIC_NAME:alarm}
      trade-result: ${KAFKA_TRADE_RESULT_NAME:trade-result}
  trade:
    start-market: ${START_MARKET:KRW-BTC}
    start-money: ${START_MONEY:10000}
    sell:
      phase1:
        wait-minute: ${PHASE_1_WAIT_MINUTE:150}
        profit-percent: ${PHASE_1_PROFIT_PERCENT:1.5}
        loss-percent: ${PHASE_1_LOSS_PERCENT:3.0}
      phase2:
        wait-minute: ${PHASE_2_WAIT_MINUTE:90}
        profit-percent: ${PHASE_2_PROFIT_PERCENT:0.1}
        loss-percent: ${PHASE_2_LOSS_PERCENT:2.0}
      profit-moving-average:
        big: ${PROFIT_MOVING_AVERAGE_BIG:30}
        small: ${PROFIT_MOVING_AVERAGE_SMALL:10}
  manager:
    url: ${MANAGER_URL:'http://localhost'}
  upbit:
    access-key: ${UPBIT_ACCESS_KEY:upbit-access-key}
    secret-key: ${UPBIT_SECRET_KEY:upbit-secret-key}



